name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
      - name: Build distribution
        run: uv build
      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
          verbose: true
